server:
 port: 8090
 servlet:
  context-path: /sharding
mybatis:
  mapper-locations: classpath:xml/*Mapper.xml
logging:
  config: classpath:logback.xml
swagger:
  enable: true
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://172.16.233.54:3306/tutorabcmember?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
    driverClassName: com.mysql.jdbc.Driver
    username: dev_account
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
